### PR TITLE
Feature player match list view

### PR DESCRIPTION
**Pull request by krisko6**
Pull request for player match-list-view. @cpascua please review.

### CODE REVIEW

**Comment by cpascua** [comment]
These are screenshots of what the app looks like on an android Samsung s6 edge android.  I don't have a ios device to test this on but we will need to make sure it works for that as well. Also, sorry for the huge screen shots.
screenshot_2015-11-09-10-24-40
screenshot_2015-11-09-10-26-54
screenshot_2015-11-09-10-26-59 1

**Comment by krisko6** [comment]
ios simulator screen shot nov 9 2015 8 38 37 pm

Here's a screenshot of what it looks like on iPhone 5. Did you remember to pull the data in from the later commits when testing this branch?

**Comment by cpascua** [comment]
Its looking alot better now after re-pulling.  The avatars are a bit off in the match view but other than that it functions as desired.  
screenshot_2015-11-09-22-04-26
I will meet with Ian to tomorrow to discuss any additions or specific changes.

**Comment by krisko6** [comment]
The match view is more of a placeholder, since the assignment was to work on the listing views.

**Comment by cpascua** [comment]
@krisko6 alright, This is ready to merged into development.  I'll create a new issue for the match view.

**Comment by krisko6** [comment]
@cpascua I've created the player- views, and I think they should be merged back into the project. Please check out the views and tell me if there are any tweaks/additions I should make before we start integrating with the backend.

**Comment by cpascua** [comment]
@krisko6 Just a minor issues with keyboard on android pushing the announcement textbox out of view.  This is something we can fix later.  This closes Issue #6. I'll go ahead and merge in these changes.

**Pull request merged**
